# Generated by Django 4.2.2 on 2023-06-28 02:46

import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=None, max_length=80, null=None, verbose_name='Title')),
                ('slug', models.CharField(blank=None, max_length=100, null=None, verbose_name='Slug')),
                ('description', models.CharField(blank=None, max_length=150, null=None, verbose_name='Description')),
                ('content', ckeditor.fields.RichTextField(verbose_name='Content')),
                ('image', models.URLField(blank=None, max_length=255, null=None)),
                ('state', models.BooleanField(default=True, verbose_name='Published/Not Published')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Creation Date')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Update Date')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.author')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.category')),
            ],
            options={
                'verbose_name': 'Post',
                'verbose_name_plural': 'Posts',
            },
        ),
    ]
